---
# tasks file for powertools

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Enable powertools
  community.general.ini_file:
    path: "/etc/yum.repos.d/{{ powertools_repo_file }}"
    section: "{{ powertools_repo_name }}"
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - Yum update cache
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"
