---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: install a powertools package
      ansible.builtin.package:
        name: libpcap-devel
        state: present
      notify:
        - remove a powertools package

  handlers:
    - name: remove a powertools package
      ansible.builtin.package:
        name: libpcap-devel
        state: absent
