---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check powertools/crb repo is enabled
      ansible.builtin.command:
        cmd: yum repolist enabled
      register: repolist
      changed_when: false

    - name: Assert powertools or crb repo is enabled
      ansible.builtin.assert:
        that: "'crb' in repolist.stdout or 'powertools' in repolist.stdout"
        fail_msg: "Neither crb nor powertools repo found in enabled repos: {{ repolist.stdout }}"
